### ISSUE TITLE
support .net core2.0

### ISSUE THREAD

**Issue by cnblogsTim** [olegtarasov/FastText.NetWrapper#1]
can support .net core 2.0?

**Comment by olegtarasov** [comment]
I'm thinking about it and it's certainly doable. I guess I will get to it in a couple of months when our own project is migrated to .net core.
Meanwhile, if anyone wants to lend a hand with porting the wrapper to .net core, I will appreciate it!

**Comment by TechnikEmpire** [comment]
I found you because I'm porting fastText to .NET core entirely (fully managed) and I was just looking to see if anyone else in the .NET world had gone there before I invested more time. I'm through the majority of it, and should only be a few more days to completion. I have trained fast text models for text classification and I want to be able to run them anywhere my heart desires without touching a C/C++ compiler, just to explain motivation. If you're interested, I can ping you when I publish it. Seems like we both an interest in building and maintaining such a thing.

**Comment by aidesigner** [comment]
TechnikEmpire, did you complete the port of fastText to .NET standard 2.0?  I would really like to take a look at the repository.

**Comment by TechnikEmpire** [comment]
@aidesigner Not yet, I have to finish the FastText class, then I need to run some tests to confirm I didn't screw anything up because I'm literally just a translator moving code between languages. :)

**Comment by olegtarasov** [comment]
With version 1.0.25 the library if finally ported to .NET Standard and now supports Windows, Linux and MacOs!

**Comment by TechnikEmpire** [comment]
@olegtarasov  Woot! Very nice. Thank you for your efforts and for sharing your work.

**Comment by olegtarasov** [comment]
@TechnikEmpire Please don't hesitate to file bug reports :) I've only had the chance to test it on MacOs for now.
