### ISSUE TITLE
NuGet Package 1.1.0 not working

### ISSUE THREAD

**Issue by Vic281** [olegtarasov/FastText.NetWrapper#19]
Hello,

first thanks a lot for the new features implemented, especially for the test method.

Unfortenately the NuGet package does not work. As soon as i install the update, i get the error:
"CS0246	The type or namespace name 'FastText' could not be found (are you missing a using directive or an assembly reference?)"

Also the package is not more referenceable by using statement (using FastText.NetWrapper;).
Installing the package 1.0.37 back again resolves the errors.

I tried with .NET Framework, .NET Standard and .NET Core, not one worked.

Could you test the package and check for any issues?

**Comment by olegtarasov** [comment]
Hi @Vic281! OK, this is unexpected. I covered almost all of the critical code with tests, but never expected for the package itself to break :)

I've reproduced the issue and will investigate it right away.

**Comment by olegtarasov** [comment]
@Vic281 I fixed the bug and pushed v. `1.1.1` to Nuget. Since you are upgrading anyway, I suggest you try version `1.2.0-preview` which introduces some breaking changes from `1.0` and `1.1` branches. You can find migration guide (which is super simple) in 1.2 readme: https://github.com/olegtarasov/FastText.NetWrapper/blob/v1.2/README.md.

I will push a final version of `1.2` in a couple of days.

**Comment by Vic281** [comment]
works, thanks! :)
