### ISSUE TITLE
How to convert vector to word?

### ISSUE THREAD

**Issue by andre-sib** [olegtarasov/FastText.NetWrapper#24]
To get a vector from a word, use the function

float[] GetWordVector(string word)

How to convert back to word?

**Comment by olegtarasov** [comment]
Hi @andre-sib! Getting word from vector with FastText is generally impossible because of subwords. When you call GetWordVector(), your word is broken down into subwords (which are learned during model training). Then FastText gets a vector for each subword, sums them and averages the result. This is a one-way operation.
